### ISSUE TITLE
custom protocols file not taking precedence over builtin dissectors

### ISSUE THREAD

**Issue by Tomasu** [ntop/nDPI#104]
I've setup a protocols file that i load, which has tcp:56000,udp:56000@Custom, but some traffic is being misdetected as Viber, Tor, and other protocols.

**Comment by kYroL01** [comment]
Please, can you provide this pcap file ? Thanks.
Viber, for example, is going to be fix, as you can see from this issue (https://github.com/ntop/nDPI/issues/78).

**Comment by Tomasu** [comment]
I didn't let it run for very long, but it's found both Viber and Tor when I'm just checking for port 56000 which theoretically only be one single protocol.

http://tomasu.net/~moose/56000.pcap

**Comment by kYroL01** [comment]
Are you sure you're using the last dev nDPI version ?
I did a test with ndpiReader, and no Viber is detected, but the most traffic is (correctly) detect as BitTorrent and Unknown:

**Unknown              packets: 2667          bytes: 2243269       flows: 54**
**BitTorrent            packets: 8193          bytes: 3579024       flows: 851**
**Skype                  packets: 28              bytes: 4995             flows: 1**
**Tor                      packets: 10              bytes: 620               flows: 1**

Also wireshark detect many BitTorrent by your pcap.
Tor packets maybe is detected cause the BitTorrent (I'll try to understand better).
I have to check for Skype dissector, because we have some false positive (issue https://github.com/ntop/nDPI/issues/86).

I close this issue, but just because is correlated to others.

**Comment by Tomasu** [comment]
Ok, sounds good. Thanks for looking into it.

**Comment by kYroL01** [comment]
You're welcome
