### ISSUE TITLE
DETECTION MIGHT NOT WORK CORRECTLY Warning

### ISSUE THREAD

**Issue by imehrdad2012** [ntop/nDPI#117]
Hello,
When I run the ndpiReader, I always get the following warning. Is it serious? How can I address it?
WARNING: packet capture size is smaller than packet size, DETECTION MIGHT NOT WORK CORRECTLY

**Comment by lmangani** [comment]
This suggests your packets are truncated, consequently dissectors and detections might not work as intended.

**Comment by kYroL01** [comment]
Hi @imehrdad2012 . This is not a nDPI problem, because, as @lmangani explain in the previous comment, this is a control inside ndpiReader to avoid truncated, corrupted or bad packets to be analized.
If you see here (https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c#L1780) ndpiReader is designed to check if the length of the entire packet matching with the one read from a field of the packet: if yes, the packet could be examined; else, it's discarded.

Are you using ndpiReader passing a pcap or live ?

**Comment by mehrdadmoradi-crusoe** [comment]
Thanks for the comprehensive response. In fact, this only happens when
capturing from an actual interface. I am not sure what the problem is.

Best Regards,
---Mehrdad

On Tue, Nov 17, 2015 at 9:27 AM, Michele Campus notifications@github.com
wrote:

> Hi @imehrdad2012 https://github.com/imehrdad2012 . This is not a nDPI
> problem, because, as @lmangani https://github.com/lmangani explain in
> the previous comment, this is a control inside ndpiReader to avoid
> truncated, corrupted or bad packets to be analized.
> If you see here (
> https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c#L1780)
> ndpiReader is designed to check if the length of the entire packet matching
> with the one read from a field of the packet: if yes, tha packet could be
> examined; else, it's discarded.
> 
> Are you using ndpiReader passing a pcap or live ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ntop/nDPI/issues/117#issuecomment-157385547.

## 

---

Mehrdad Moradi
‌Research Assistant
University of Michigan- Ann Arbor

**Comment by lmangani** [comment]
This could be an issue with your port monitoring/mirroring settings affecting large packets

**Comment by kYroL01** [comment]
@imehrdad2012 You're welcome !
