### ISSUE TITLE
Why kernel directives were removed?

### ISSUE THREAD

**Issue by betolj** [ntop/nDPI#120]
I'm keeping one ndpi-netfilter fork here:
https://github.com/betolj/ndpi-netfilter

I had to return many directives such as "#ifndef **KERNEL**" manually. Why?
https://github.com/betolj/ndpi-netfilter/tree/master/nDPI-patch/src

**Comment by lucaderi** [comment]
You have contributed to this https://github.com/ntop/nDPI/issues/22 so you know the story. We did that because I do not think DPI should happen in the kernel but I am open to keep it. The point is that there are so many fork and sub-forks for this feature, that make difficult to maintain it. I suggest you to sync with the other kernel-DPI developers and send a merge request (one) so that we can consolidate all the kernel work in nDPI. Instead if you want to still keep your fork alive, for me is ok, but then we have to be free to make changes to nDPI we consider are reasonable.
