### ISSUE TITLE
Kerberos,LDAP features how can i use in nfstream?

### ISSUE THREAD

**Issue by imagineTh4t** [ntop/nDPI#1339]
I want to get Kerberos features(domain,username,hostname,etc.) and LDAP features from nDPI on nfstream. I see kerberos.c in nDPI but i dont know how to use. Can you help me about it ?

**Comment by utoni** [comment]
This sounds more like an nfstream issue. You can open an issue [here](https://github.com/nfstream/nfstream/issues). Make sure to read the documentation first.

I do not know much about nfstream, but @aouinizied does.

**Comment by imagineTh4t** [comment]
Are you editor or admin ? @lnslbrty

**Comment by utoni** [comment]
Collaborator, I guess.

**Comment by imagineTh4t** [comment]
Do you know anything about my question? Can you help me?

**Comment by utoni** [comment]
If your question is related to nDPI, I might be able to help you. But nfstream is none of my business. Your question needs to be more specific, otherwise I can just give you some general information.

Take a look at [ndpiSimpleIntegration.c](https://github.com/ntop/nDPI/blob/dev/example/ndpiSimpleIntegration.c). This example shows howto process packets with nDPI and prints some information about dissected protocols. In that example only TLS related information is shown. But it is adaptable to print LDAP/Kerberos related information with very little effort.

**Comment by aouinizied** [comment]
@imagineTh4t This is related to nfstream and not nDPI as nDPI already extract such features. Please open an issue on NFStream project


Zied
