### ISSUE TITLE
Instagram Misclassification in GTP <QUIC> flows

### ISSUE THREAD

**Issue by vanggelis** [ntop/nDPI#1364]
Further to the attached pcap, the corresponting IP flow is not further classified to instagram. It seems that the `tls.handshake.extensions_server_name` is not being examined by the DPI module.

[quic_flow.zip](https://github.com/ntop/nDPI/files/7427244/quic_flow.zip)

**Comment by IvanNardi** [comment]
It works for me
```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ ./example/ndpiReader -t -i ~/quic_flow.pcap -v2 -I
[...]
	1	UDP 10.168.233.233:38335 <-> 195.14.146.162:443 [proto: GTP:188.211/QUIC.Instagram][Encrypted][cat: SocialNetwork/6][3 pkts/3259 bytes <-> 6 pkts/2293 bytes][Goodput ratio: 92/79][0.04 sec][ALPN: h3-fb-05][TLS Supported Versions: TLSv1.3][bytes ratio: 0.174 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 1/0 18/7 35/35 17/14][Pkt Len c2s/s2c min/avg/max/stddev: 591/105 1086/382 1334/1314 350/426][TLSv1.3][Client: instagram.fnic2-2.fna.fbcdn.net][JA3C: 909b789c7247986bee7fe7d6662b3c43][PLAIN TEXT (cHRdyL)][Plen Bins: 11,22,0,0,0,11,0,0,11,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,22,0,0,0,0,0,0,0,0]
```
Note the "-t" flag (to decapsulate GTP-U traffic) and the "-I" flag (because you have upstream and dowstrem packets in different vlans)

Am I missing something obvious here?

**Comment by vanggelis** [comment]
Hello Ivan,

Actually the classification of the particular quic flow requires libgcrypt20 which is not available in the Ubuntu12.04 and CentOS7 where I performed the test. 

Is there any workaround for this?

**Comment by utoni** [comment]
libgcrypt is mandatory to decrypt QUIC client hello's because newer IETF- and Google- QUIC versions contain encrypted TLS1.3 handshakes but the decryption keys are publicly available.
That may be the reason why you do not get any server names for that flow.

You can try to compile libgcrypt from source.
From my point of view there is no need for nDPI to support ancient distributions.

**Comment by IvanNardi** [comment]
> You can try to compile libgcrypt from source.

Some time ago, I was able to use ndpi on CentOS7 compiling libgcrypt 1.8.6 myself. I don't remember much, but it definitely worked

**Comment by vanggelis** [comment]
Thank you for the information Ivan.

**Comment by vel21ripn** [comment]
@IvanNardi  The minimum libgcrypt version required for nDPI  is 1.9.2. It would be nice to add this restriction to configure.ac. Older versions of libgcrypt fail testing with --with-sanitizer.
Libgcrypt versions prior to 1.9.1 have serious vulnerabilities.

**Comment by IvanNardi** [comment]
> @IvanNardi The minimum libgcrypt version required for nDPI is 1.9.2. It would be nice to add this restriction to configure.ac. Older versions of libgcrypt fail testing with --with-sanitizer.
> Libgcrypt versions prior to 1.9.1 have serious vulnerabilities.

@vel21ripn, I can't comment on libgcrypt vulnerabilities, but I would like to have more information about your environment and about the errors you are seeing.
I am asking that, because  I usually use nDPI on x86_64, Ubuntu 20.04 with libgcrypt 1.8.5 (the version provided by Ubuntu itself) and with asan without any issue. (In the previous messages when I talked about 1.8.6, it was about CentOS 7, without asan)
