### ISSUE TITLE
Adapting nDPI to use another crypto lib

### ISSUE THREAD

**Issue by viniciussn** [ntop/nDPI#1424]
Hello, 

I using nDPI in some embedded applications and its working gracefully.
But in some devices that we are working with, the available storage is extremely low (a few megabytes). 
One of the biggest dependencies of nDPi is libgcrypt + libgperror (~2.5 MB), used for QUIC decryption.
These devices uses OpenSSL and have their crypto library (libcrypto).

My question is: Is it possible to adapt nDPI to use another crypto lib (e.g. libcrypto) in a easily way?

**Comment by IvanNardi** [comment]
A similar request has been already made in the past: #1120
I think that nothing changed since then: it is probably feasible to use another cypto library; the hard part is finding someone doing the real work :-)
Note that @vel21ripn is doing something somehow similar (but for completely different reasons, IMO): https://github.com/vel21ripn/nDPI/commit/4f8fce9909c07e2016cab6e2e0899647d7b797c9

**Comment by viniciussn** [comment]
I'll check. Thank you.
