### ISSUE TITLE
Need help in classification of protocol and subprotocols

### ISSUE THREAD

**Issue by JeevanNailwal** [ntop/nDPI#163]
Hi all,
Can you please help me to get the document which can tell me , out of 219 available protocol-ids, which all protocol ids comes in protocol region(like HTTP, HTTPS) and which all protocol ids are in subprotocol section(skype, bittorrent)?

In addition, can someone please explain on the linking on various kind of protocol identities.
Basically, different types of protocol NDPI_SERVICE_..... , NDPI_CONTENT_..... , NDPI_PROTOCOL_..... ,  NDPI_PROTOCOL_IP_..... ?
Which of these comes under protocol and which one are in subprotocol version?

Thanks,
Jeevan

**Comment by kYroL01** [comment]
[Here](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocol_ids.h) you can see the list of all the availlable protocols/subprotocols detected by nDPI associated to their IDs.

I try to explain better.
First of all, _protocols_ are considerd "real" protocols like HTTP, SSL, DNS; _subprotocols_ are the application protocols detected over protocols thanks to flows like Facebok, Skype, BitTorrent, Whatsapp (nDPI is interested in detection by flows, not single packets as a packet sniffer).
Second: not all the protocols could be detected with a proper dissector (unfortunately many application don't reveals their features and try a reverse engineering is not so easy (often impossibile), specially with encrypted traffic. This is why some protocols are detected by ports or IP host addresses that (luckily) help us. These protos are called as **NDPI_SERVICE**.
The others explain above are **NDPI_PROTOCOL**.
The **NDPI_PROTOCOL_IP** are necessary to show protocols that have only IP level (nDPI otherwise does not show flows with **only** IP or Transport level).
**NDPI_CONTENT** are for protocols containing multimedial contents, like AVI, FLASH, MPEG...

Hope to _shine_ on you.

**Comment by JeevanNailwal** [comment]
Thanks for the reply Michele.

Just one more query, as you said that "protocols are considerd "real" protocols" so that means all other types i.e. SERVICE, PROTOCOL_IP and PROTOCOL_CONTENT... they all come in subprotocol catogory?

**Comment by kYroL01** [comment]
In a way, yes.
But there are applications that is detected sometimes as protocols (with its dissector) sometimes as service (and the protocol is (for example) SSL or HTTPS.
