### ISSUE TITLE
compile nDPI output /usr/bin/ld: cannot find -lnuma

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#174]
When I compile the nDPI source code, `make`, the  output is:  **/usr/bin/ld: cannot find -lnuma** Thanks!

**Comment by kYroL01** [comment]
It seems you missed the NUMA lib (Non Uniform Memory Access). Which nDPI version do you use ? 
Can you post the output of makefile ?
Maybe you just need `apt-get install libnuma-dev`

**Comment by tianzhishuizhu** [comment]
I use the latest version on github. Do you mean the whole file `Makefile` in the nDPI directory?

**Comment by tianzhishuizhu** [comment]
I try sudo apt-get install libnuma-dev, and there is no error output about -lnuma. The `make` output is:

```
libtool: link: ranlib .libs/libndpi.a
libtool: link: ( cd ".libs" && rm -f "libndpi.la" && ln -s "../libndpi.la" "libndpi.la" )
make[2]: Leaving directory `/home/hu/nDPI/src/lib'
Making all in example
make[2]: Entering directory `/home/hu/nDPI/example'
depbase=`echo ndpiReader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DHAVE_CONFIG_H -I. -I..  -I../src/include -I /home/hu/PF_RING/userland/libpcap  -pthread -g -O2 -MT ndpiReader.o -MD -MP -MF $depbase.Tpo -c -o ndpiReader.o ndpiReader.c &&\
    mv -f $depbase.Tpo $depbase.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -pthread -g -O2 -static  -o ndpiReader ndpiReader.o ../src/lib/libndpi.la   /home/hu/PF_RING/userland/libpcap/libpcap.a /home/hu/PF_RING/userland/lib/libpfring.a -lnuma  -lrt     -lrt 
libtool: link: gcc -pthread -g -O2 -o ndpiReader ndpiReader.o  ../src/lib/.libs/libndpi.a /home/hu/PF_RING/userland/libpcap/libpcap.a /home/hu/PF_RING/userland/lib/libpfring.a -lnuma -lrt -pthread
make[2]: Leaving directory `/home/hu/nDPI/example'
make[2]: Entering directory `/home/hu/nDPI'
make[2]: Leaving directory `/home/hu/nDPI'
make[1]: Leaving directory `/home/hu/nDPI'
```

Has nDPI been correctly installed?

**Comment by kYroL01** [comment]
I think it's correctly installed, but:

yours:
`/bin/bash ../libtool  --tag=CC   --mode=link gcc -pthread -g -O2 -static  -o ndpiReader ndpiReader.o ../src/lib/libndpi.la   /home/hu/PF_RING/userland/libpcap/libpcap.a /home/hu/PF_RING/userland/lib/libpfring.a -lnuma  -lrt     -lrt 
libtool: link: gcc -pthread -g -O2 -o ndpiReader ndpiReader.o  ../src/lib/.libs/libndpi.a /home/hu/PF_RING/userland/libpcap/libpcap.a /home/hu/PF_RING/userland/lib/libpfring.a -lnuma -lrt -pthread`

mine:
`/bin/bash ../libtool  --tag=CC   --mode=link gcc -pthread -g -O2 -I/usr/include/json-c -static -ljson-c -o ndpiReader ndpiReader.o ../src/lib/libndpi.la   -lpcap 
libtool: link: gcc -pthread -g -O2 -I/usr/include/json-c -o ndpiReader ndpiReader.o  ../src/lib/.libs/libndpi.a -ljson-c -lpcap -pthread`

Are u installed PF_RING ? It seems that your makefile link lnuma and the error rise-up because it cannot find that library.

Are you tried again after installed libnuma-dev ?

**Comment by tianzhishuizhu** [comment]
I don't install PF_RING. I just want to test nDPI and ndpiReader. Yeah, I have tried again and it can work.

**Comment by kYroL01** [comment]
GOOD! :)

I close the issue.
