### ISSUE TITLE
Potential NULL pointer dereference

### ISSUE THREAD

**Issue by ProjectMutilation** [ntop/nDPI#1792]
Hi, guys, I found the suspicious implementaion of function. 
src/lib/protocols/rtp.c:131(at commit 9e73d61fb04)  in ndpi_search_rtp pointer "packet->udp"  was dereferenced before it was checked against null. 
```
 u_int16_t source = ntohs(packet->udp->source);
  u_int16_t dest = ntohs(packet->udp->dest);
...
if((packet->udp != NULL)
```
May be it's error?
Perhaps it is worth adding a check before dereferencing for assignment source and dest?
```
if((packet->udp == NULL) {
NDPI_EXCLUDE_PROTO(ndpi_struct, flow);
}
```

**Comment by IvanNardi** [comment]
`ndpi_search_rtp()` is called only for UDP flows (because of `NDPI_SELECTION_BITMASK_PROTOCOL_V4_V6_UDP_WITH_PAYLOAD`) so it is always safe to dereference `packet->udp` pointer, IMO

Did you find the issue simply looking at the code or "for real"? (e.g. via [oss-sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz)?)

Nonetheless, as you noticed, the code is not clear and can be improved: I am going to remove that useless check.
Thanks for the report

**Comment by ProjectMutilation** [comment]
@IvanNardi static analyzer Svace detected about it as potential dereference or superfluous checking

**Comment by IvanNardi** [comment]
@ProjectMutilation , definitely a  superfluous checking. I'll update the code
