### ISSUE TITLE
Non-DNS traffic detected as DNS - IP tunnel over DNS

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#192]
I want to know the process of detecting **DNS** protocol. Does the process only use known port?No dpi method(**Layer7 inspect**) used for detecting DNS? Thanks! 
 In function **ndpi_search_dns()**  `if((s_port == 53 || d_port == 53 || d_port == 5355) && (flow->packet.payload_packet_len > sizeof(struct ndpi_dns_packet_header)))`

**Comment by Mile-Lile** [comment]
OpenDNS can listen on port 443...
There is something called IP-over-DNS... Iodine creates tunnel over port 53 http://code.kryo.se/iodine/
so, I hope nDPI can search dns traffic on other ports...

**Comment by kYroL01** [comment]
@tianzhishuizhu if you see better in the dissector, there are many checks to inspect the payload (for example to see if a dns is a query or a response, or to extract host name server, but I think that I need to check better.
Thank you @Mile-Lile i didn't know this.

**Comment by kYroL01** [comment]
I did a test with a dns tunnel iodine pcap and nDPI detect all the packets as DNS correctly.
@tianzhishuizhu @Mile-Lile The check on port **53** is necessary because DNS flows _for sure_ on this source or destination ports ( https://technet.microsoft.com/en-us/library/dd197515(v=ws.10).aspx ), then, we apply dpi method to detect if that packet is really a dns.

If you find dns packets that not use port 53 in source or dest, please, provide a pcap.
Thanks

**Comment by Mile-Lile** [comment]
> I did a test with a dns tunnel iodine pcap and nDPI detect all the packets as DNS correctly.

It shouldn't be detected as DNS... because iodine just uses port 53 for all traffic (to avoid ISP restrictions such as Great China Firewall). All traffic, such as http, p2p etc goes through tunnel (src pt 53 and dsp pt 53)... so not sure if it works good...

I can't provide pcap because I use wireshark on PC to grab traffic and my home router can redirect dns request on other non standard dns port... use linux and iptables and do:

`iptables -t nat -I PREROUTING -p tcp --dport 53 -j DNAT --208.67.222.222:443

iptables -t nat -I PREROUTING -p udp --dport 53 -j DNAT --208.67.222.222:443`

I am not talking about DNSCrypt
 read this:

https://support.opendns.com/entries/52311880-DNS-requests-for-FamilyShield-servers-are-hijacked-by-ISP

**Comment by kYroL01** [comment]
@Mile-Lile Thanks a lot for clarification. I have to investigate better.
Can you open a specific issue for this to focus better the problem ?
Thank you

**Comment by Mile-Lile** [comment]
Yes I can, but I must find way to catch pcap first. My wireshark is behind my router firewall where I can do dns port redirection... I'll back to you in few days... maybe to do nslookup from my PC to OpenDNS 5353 and 443 port while wireshark is running...

**Comment by kYroL01** [comment]
Take your time and thanks also to @tianzhishuizhu for evidence that.

**Comment by Mile-Lile** [comment]
Oh yes:) OpenDNS listens on port 443... try it yourself... from windows machine do:

`nslookup -type=a -port=443 www.blic.rs 208.67.222.222`

I got this answer:

`C:\Users\hmilenkovic>nslookup -type=a -port=443 www.blic.rs 208.67.222.222
Server:  resolver1.opendns.com
Address:  208.67.222.222

Non-authoritative answer:
Name:    blicrs.dreamlab.pl
Address:  185.104.64.10
Aliases:  www.blic.rs`

**Comment by kYroL01** [comment]
Maybe for OpenDNS we just filter by IP as describe [here](https://en.wikipedia.org/wiki/OpenDNS#Name_Server_IP_Addresses)

**Comment by Mile-Lile** [comment]
as a matter of fact I think it is very good idea! Even if dns traffic is encrypted (when using DNSCrypt protocol, which authenticates DNS traffic between the user's computer and the name servers on port 443) it will use OpenDNS resolver IPs... so adding OpenDNS resolvers IPs will help... I don't know any other free service listening on non standard dns port... but I can tell you OpenDNS is very popular within sys admin because of the filtering posibilities... They are part of Cisco now.

**Comment by tianzhishuizhu** [comment]
@kYroL01  You are welcome. Your work is really appreciated!

**Comment by kYroL01** [comment]
It's not only mine, all the contributions are important ;)

**Comment by kYroL01** [comment]
https://github.com/ntop/nDPI/commit/ccdcf9d82b5e599beb7e9f96acd767110b0aa965
@Mile-Lile test need

**Comment by Mile-Lile** [comment]
[trace.zip](https://github.com/ntop/nDPI/files/268805/trace.zip)

I will try to provide pcap with non dns traffic on port 53. I'll try... first I have to figure it out how:) Trace above is OpenDNS trace...

**Comment by kYroL01** [comment]
Thanks a lot. I'll do many test

**Comment by kYroL01** [comment]
I tried and even if I putted the cidr for OpenDNS ip address, nDPI doesn't detect correctly. I think is not a dns problem but an internal bug in nDPI.
I have to check better.

**Comment by Mile-Lile** [comment]
[IP_tunnel_over_DNS.zip](https://github.com/ntop/nDPI/files/273421/IP_tunnel_over_DNS.zip)

here is the pcap I promised. This is non dns traffic through dns port.... ip over dns tunnel is accomplished with software developed from these guys: https://your-freedom.net/

**Comment by kYroL01** [comment]
@Mile-Lile huge work man. Thank you so much! ;)

**Comment by lucaderi** [comment]
This traffic is not detected properly as suspicious via Flow Risk

UDP 192.168.2.95:55131 <-> 94.126.23.44:53 [proto: 5/DNS][cat: Network/14][16 pkts/2096 bytes <-> 16 pkts/3040 bytes][Goodput ratio: 68/78][30.10 sec][Host: lx.3xa2ytu5rt3giwsaf8hp9plhz5eoach9c3t2exzzivsemr.s24.2yf.de][::][bytes ratio: -0.184 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 1992/1975 1999/1999 2010/2022 5/11][Pkt Len c2s/s2c min/avg/max/stddev: 131/190 131/190 131/190 0/0][Risk: ** Suspicious DGA domain name **** Suspicious DNS traffic **][PLAIN TEXT (giwsaf8)][Plen Bins: 0,0,50,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
