### ISSUE TITLE
Can the latest ndpi version still support hyperscan?

### ISSUE THREAD

**Issue by Rranveryverysix** [ntop/nDPI#1938]

**Comment by IvanNardi** [comment]
Hyperscan support has been removed in https://github.com/ntop/nDPI/commit/2ccd2c204bcc3f272cf19e03978a0c2c998386af because https://github.com/ntop/nDPI/issues/1135#issuecomment-782101929
If you *really* want to try it, you could try to manually revert that commit on your local repository; it shouldn't be rocket science but it might be very painful.
AFAIK there is not plan to bring it back in the current code; pinging @lucaderi

**Comment by lucaderi** [comment]
Not planned as hyperscan implemented various pattern matching algorithms that we do not need and that are slowing down the system. Furthermore is (used to be, or still is) a x64-only software that will limit nDPI to one platform.
