### ISSUE TITLE
What's the method used in nDPI to discover features of an application's payload

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#195]
What's the **method or algorithm** used in summarying features of an application's payload? Are these features found by programmers inspecting every packet or Automation method？Thanks! Because there are so many applications and protocols. How to improve efficiency to summary features of application's payload?

For example, for detecting application qq, qq.c comment is:

```
/*a qq client packet looks like this:
 *
 * TCP packets starts with 16 bit length, then the normal packets follows
 * 
 * 0 1 byte packet tag (usually 0x02)
 * 1 2 byte client tag (client version)
 * 3 2 byte command
 * 5 2 byte sequence number
 * 7 4 byte userid
 * 11 x bytes data
 * LAST 1 byte packet tail (usually 0x03)
```

**Comment by kYroL01** [comment]
There are many protocols, and every application packet has its own payload, so it's impossible to use a unique _method_.
Not all the protocols are detected by official specifications, because many companies don't release them. Solution ? try to understand with reverse engeneering of packets and flows.
So to answer your question in a speech, _it depends on the application_.

**Comment by tianzhishuizhu** [comment]
@kYroL01  Yeah. I will study reverse engineering of packets and flows. Can you instruct me a document about the topic of *\* reverse engineering of packets *\* or a link of wiki about it? I'm worrying about searching false information. Thanks for your reply.@kYroL01  Can you help me ?
