### ISSUE TITLE
Most optimimal usage of nDPI

### ISSUE THREAD

**Issue by stathisgotsis** [ntop/nDPI#282]
I am wondering what is the simplest and most optimal usage of nDPI in a flow processing application. I go with the following code for initialization:

`struct ndpi_detection_module_struct *ndpi_module = ndpi_init_detection_module();`
`ndpi_module->http_dont_dissect_response = 1;`

`NDPI_PROTOCOL_BITMASK all;`
`memset(&all, 0xFF, sizeof(all));`
`ndpi_set_protocol_detection_bitmask2(ndpi_module, &all);`

And then for each packet in a flow:

`struct ndpi_id_struct src, dst;`
`memset(&src, 0, sizeof(src));`
`memset(&dst, 0, sizeof(dst));`

`ndpi_protocol protocol = ndpi_detection_process_packet(ndpi_module,`
`                                         ipflow_ndpi, // ndpi state machine inside ipflow`
`                                         ip_header_ptr, // pointer to IP header`
`                                         ip_total_length, // IP total length`
`                                         timestamp, // timestamp`
`                                         &src,`
`                                         &dst);`

until either protocol.master_protocol or protocol.protocol is not NDPI_PROTOCOL_UNKNOWN, when the flow is considered as service classified. 

Would that be the most optimal usage? Or am I better off with e.g. ndpi_l4_detection_process_packet()?

**Comment by emanuele-f** [comment]
You can look at/use the routines implemented in https://github.com/ntop/nDPI/blob/dev/example/ndpi_util.h /.c file, which simplify your life a lot. It is still an experimental API but it can used to esily setup things and write a clean program. Take a look at https://github.com/emanuele-f/DNSleak for an usage example.

**Comment by kYroL01** [comment]
in nDPI there are many important data structures:
`struct ndpi_detection_module_struct` and `struct ndpi_flow_struct` are the two main structures to pass to function to keep the status of the work (i.e. look https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_api.h#L300).
Inside a flow, every packets are dissect to understand how is the own protocol.

As @emanuele-f says, take a look at that file to understand better the core of the main structures.
A thing you have to keep in mind is for proto classification dissectors are applied sequentially starting with the one that will most likely match the flow.

The **bitmap** mask is used to avoid useless cycle in detection: each flow maintains the state for non-matching dissectors in order to skip them in future iterations.

**Comment by stathisgotsis** [comment]
Thanks for your suggestions. I am doing the ip flow accounting / engine myself, that is why I chose to only use: ndpi_detection_process_packet, as I showed above. However, as a result, I see a lot of flows with ports 80,443 to remain unclassified; I suppose I need to do ndpi_find_port_based_protocol() before ndpi_detection_process_packet()?

**Comment by kYroL01** [comment]
The classification is done by port matching and dissectors. If you don't have this you cannot classify properly.
