### ISSUE TITLE
detected services and protocol test pcaps insufficient

### ISSUE THREAD

**Issue by waqas-latif** [ntop/nDPI#299]
I am testing ndpi to check which services and protocol it detects. Ofcourse, I went through the protocol list on the [website](http://www.ntop.org/products/deep-packet-inspection/ndpi/) and also from the [ndpi_protocol_ids.h](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocol_ids.h). When I used the test pcaps from the repo, it didnt detect all the listed protocols(see attached nDPI_protocol_report.json). I had some extra pcap files, which when I passed that to ndpi(see attached nDPI_protocol_report2.json), more protocols are triggered than before, but still could not trigger all the acclaimed protocols. It would be great if you could update the test pcap files when you add support for protocols in nDPI. I mean you must have tested them before releasing the next upgrade, so why not add the test pcaps.

[reports.zip](https://github.com/ntop/nDPI/files/600096/reports.zip)

**Comment by kYroL01** [comment]
The list you see in the webpage is made before version 1.8, so in the meanwhile any protocols are added, any fixed and any deleted.
I.e. I saw your list and I did a test with a protocol you say not detected, Netflix.
Here the screenshot about Netflix detection:
![netflix](https://cloud.githubusercontent.com/assets/7222956/20436634/46218d1e-adb1-11e6-8894-cc583277ebe4.png)
So, it is detected.
The same for FTP_CONTROL, that is properly detected.
Then I saw you consider "not detected" the UNKNOWN protoocl, that is strange because if a protocol is not detected always return UNKNOWN.

I'm agree with the fact that we have to upgrade the list on internet, but we cannot put all the pcap tests for every detected protocols on the tests directory; we put only few.

If you have some undetected protocol you notice, please open a new issue and attach it a pcap for the protocol or application you think is not properly detected.
Thank you.
