### ISSUE TITLE
String Pattern Matching....??

### ISSUE THREAD

**Issue by p2yogi** [ntop/nDPI#317]
Hi, 

ndpi_detection_process_packet() API is called with particular arguments and we get result as application/protocol ID.

As DPI supports string pattern matching, so does ndpi has any api which does this....??
like: Any url with some string as keyword which could be detected by nDPI library and further can be used...??

Are any other API s...??

**Comment by k0ste** [comment]
> Are any other API s...??

https://github.com/max197616/extfilter (block resources only).

**Comment by p2yogi** [comment]
Hi,

  I could not understand much in above link due to being unaware about the language. Please explain it in English if possible.

Thanks for the help....!!

**Comment by k0ste** [comment]
@p2yogi, this project analyze via nDPI ssl/http packets. After this search patterns uri. If pattern match - to source address sends HTTP 301 with redirect URL, if packet's encrypted to source address sends TCP RST flag. As I say above this project for block user requests via [Roskomnadzor](https://en.wikipedia.org/wiki/Federal_Service_for_Supervision_in_the_Sphere_of_Telecom,_Information_Technologies_and_Mass_Communications) ban list. You can use it, or you can fork it for their needs.

On nDPI `ndpi_protocol_match host_match[]` - for match by host you can define own hosts, but I think is not you looking for, because this is not dynamic.

**Comment by p2yogi** [comment]
Hi @k0ste,

Ok I get it. Thanks for your reply. 

From your above post I have one more query. In above project DPDK is used with nDPI library. Which means one would be passing struct rte_mbuf packet to ndpi library for application identification. So how does that work. Since ndpiReader demo example works on live packets.

And if you pass your own packet to "ndpi_detection_process_packet()" API for application identification, how are particular arguments required by the API passed with...??

Thanks for your help ... !!

**Comment by kYroL01** [comment]
@p2yogi What are you looking for ? Do you need a function to looking for a host name inside a url to say "this is app1", "this is app2" ? Maybe something like that https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_api.h#L95 ?

In `ndpi_detection_process_packet` the ID is obtain by another function, https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L3529 .

nDPi work by extracting host name server, from application they have, inside dissectors, and then check if host name matches with someone in `ndpi_content_match.c.inc`.
Not all the work is done in `ndpi_detection_process_packet` obv.

Then, if you have an IP and you wanna get the ID protocol based on that IP, you need https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_api.h#L107 .
