### ISSUE TITLE
master_protocol

### ISSUE THREAD

**Issue by vpiserchia** [ntop/nDPI#349]
Hello nDPI developers,

may ask you a clarification about the difference between these two fields in the ndpi_proto struct

typedef struct ndpi_proto {
  u_int16_t master_protocol /* e.g. HTTP */, protocol /* e.g. FaceBook */;
} ndpi_protocol;

It seems to me that the protocol field is always present, and this is not true for the master_protocol one.
Is this because you can have a first match on the "protocol" field and then you can set the master_protocol?

wouldn't be better to reverse the logic, and having a sub_protocol field instead?

thank you for any answer

**Comment by kYroL01** [comment]
@vpiserchia Try to shine you:
1) the master_protocol is the protocol that carries a possible application protocol (i.e master = HTTP, protocol = Facebook, just in case the protocol does not match immediately with the dissector.
For example we can have a detection for Skype or SSL.Skype. The difference is that in the first case the detection is cause by the dissector, in second it is by name of host name in the certificate or in other field of SSL.
2) You are right when you say " _the protocol field is always present_"; this is because for a dissector match we fill the protocol field. Maybe the confusion is for this behaviour, isn't it ?

I'm doing to do some modification, and I also trying to consider this suggestion.
Thanks for the question.
