### ISSUE TITLE
app_protocol and master_protocol

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#352]
sometimes `master_protocol` is unknown even when the `app_protocol` is not. This causes some known flows to be recognized as unknown by ntopng.

Here's a print of `app_protocol` and `master_protocol` for some flows

```
 string SSL 0
 string Unknown 0
 string SSL 0
 string Dropbox 0
 string Dropbox 0
 string SSL 0
 string Skype 0
```
is this the expected behaviour?

**Comment by kYroL01** [comment]
In some cases yes, it is expected.
For example look at this [function](https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L4457).
Have you found some strange behaviour related to https://github.com/ntop/ntopng/issues/1046 ?

**Comment by kYroL01** [comment]
> This causes some known flows to be recognized as unknown by ntopng

I think this is a possible bug, because in nDPI a flow is unknown only if both fields are unknown.
If an application protocol is detected directly by a dissector, `master_protocol` could be unknown; if instead is detected by hostname or by another dissector, it has both fields marked != unknown.

Is it possibile that nDPi and ntopng detection policy in that specific case are now different ? This could explain the ntopng issue, IMHO.

**Comment by kYroL01** [comment]
Hi @simonemainardi this fix https://github.com/ntop/ntopng/commit/8bdfa8a09b79f38ed8a796789d36cebe4d325dc7
solve the issue ?

**Comment by simonemainardi** [comment]
still need to carry on some tests

**Comment by kYroL01** [comment]
Ok thanks

**Comment by simonemainardi** [comment]
ntop/ntopng#1046 is fixed via https://github.com/ntop/ntopng/commit/c286fd5e5fa709753060f1cae29ba08c267508f9

**Comment by kYroL01** [comment]
Thanks! ;)
