### ISSUE TITLE
Build with JSON-C not possible

### ISSUE THREAD

**Issue by mluethi** [ntop/nDPI#467]
Hi.

I'm trying to build nDPI from the repo - and I want it to support JSON-C.
This doesn't work the standard way as described in http://www.ntop.org/get-started/download/

That's what I do:
```
mkdir ~/Documents/Repos
cd ~/Documents/Repos
git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
./configure --with-pic --enable-json-c
make
```

Test:
```
~/Documents/Repos/nDPI/example/ndpiReader -i ~/Documents/PCAPs/abc.pcapng -j ~/Documents/PCAPs/abc.json
WARNING: this copy of ndpiReader has been compiled without JSON-C: json export disabled
```

JSON-C is installed:
```
dpkg -l | grep libjson
ii  libjson-c3:amd64                          0.12.1-1.1                           amd64        JSON manipulation library - shared library
ii  libjson-glib-1.0-0:amd64                  1.2.8-1                              amd64        GLib JSON manipulation library
ii  libjson-glib-1.0-common                   1.2.8-1                              all          GLib JSON manipulation library (common files)
ii  libjsoncpp1:amd64                         1.7.4-3                              amd64        library for reading and writing JSON for C++
```

System config:
```
uname -m = x86_64
uname -r = 4.12.0-kali2-amd64
uname -s = Linux
uname -v = #1 SMP Debian 4.12.12-2kali1 (2017-09-13)
```

What's wrong with how I do it?
Maybe it is related to #169?

Thank you for your help!

**Comment by mluethi** [comment]
Hi.

It seems that I solved it by myself.
Next to installing the essential packages:
```
sudo apt-get install build-essential
sudo apt-get install git autoconf automake autogen libpcap-dev libtool
```


I added these as well:
```
sudo apt-get install pkg-config
sudo apt-get install libjson-c-dev
```


Now, doing this:
```
./configure --with-pic --enable-json-c
make
```

works to get a version which supports json-c.

May I propose to add these instructions to **README.nDPI**?
Note: this is only tested for Debian...

Thanks.

**Comment by kYroL01** [comment]
i'll check asap. Thanks

**Comment by kYroL01** [comment]
https://github.com/ntop/nDPI/commit/ed830d24747dba810712156d9e05be0b3a811235

**Comment by more76** [comment]
hi 
i have the exact same problem.
i tried the standard way as described in http://www.ntop.org/get-started/download/
i am using freebsd and searched a lot but couldn't find anything.
i tried this:
`git clone https://github.com/ntop/nDPI.git`   
`cd nDPI`
`./autogen.sh`
`./configure --with-pic --enable-json-c`
`gmake`

i have installed essential packages for freebsd and Json-c is installed too.here is my test:
`./ndpiReader -i alc0 -s 10  -j ~/Documents/abc.json`
`WARNING: this copy of ndpiReader has been compiled without json-c: JSON export disabled`

and my system config is:
`amd64
FreeBSD
11.1-RELEASE-p15
`

what should i do to fix this?i couldn't find freebsd version of  libjson-c-dev so that doesn't work for me. 
thanks a lot.

**Comment by more76** [comment]
@mluethi @kYroL01 don't you have any idea about my problem?
