### ISSUE TITLE
Using DNS queries to improve detection

### ISSUE THREAD

**Issue by khaled-hamwi** [ntop/nDPI#502]
I believe we can make use of DNS traffic to improve library detection. By looking at DNS responses, we can find out the "dynamic" IPs related to specific domain(s) which can then be related to specific service provider.
The nDPI contains list of IPs' ranges for each service provide that can be used for detection. This can be further improved by DNS responses in case no other detection works.

**Here is an example:**
When the trace contains a DNS response saying that "e3.whatsapp.net" is resolved to "158.85.48.247". Any flow which has been undetected by the library and destined to IP 158.85.48.247 can be considered as WhatsApp traffic.

What do you think?

**Comment by kYroL01** [comment]
Hi.
I think this behaviour is strictly associated to the actual behaviour that nDPI do when processing DNS packets.
If it's extracted **e3.whatsapp.net** during dissection, the flow from there is considered whatsapp if there is a match in the host names list.
You say: "If there is no match, resolve the name into IP and check with the ones in the list", but this is already done before, because every IPs are checked with Ips in the list.

If I understand bad, please, explain me better the case you propose.

Thanks

**Comment by khaled-hamwi** [comment]
According to my understanding, DNS traffic like e3.whatsapp.net is considered whatsapp as DNS.WhatsApp. This is OK so far. I am talking about looking at the IPs returned in A records which is not implemented as far as I can tell.

This will support the IP list already coded in indpi_content_match.c.inc file. I faced this issue when trying to do sample traces. Some flows are detected as whatsapp, but other are not. Some IPs are not included in the IP list, but can be extracted from passing A records in DNS responses.

I previously captured a trace then passed to ndpiReader. I found that flow to IP 169.45.210.75 was undetected by the library. Looking up this IP in the A records in DNS responses, I was able to find it is related to WhatsApp (DNS query for e3.whatsapp.net).

I hope you understand my explanation :)

**Comment by kYroL01** [comment]
@khaled-hamwi thanks for the explanation. Now I understand.
Yes, This is a feature that we should be implemented. Thank you very much,

**Comment by dsokoloski** [comment]
@khaled-hamwi 
> Some flows are detected as whatsapp, but other are not. Some IPs are not included in the IP list, but can be extracted from passing A records in DNS responses.

Yes this is the problem with hard-coding things like IP blocks in to compiled code.  Your idea about adding a DNS AR cache is exactly what we had to do to vastly improve application detection.  For us, a lot of traffic was not being classified.  For example, a big one was Netflix, specifically the main Netflix audio/video stream which is done over HTTP.  The HTTP _Host_ field has an IP address in there, not a nice hostname ending in nflxvideo.net, etc... So we had to do a few things:

- Enable DNS response dissection in nDPI (ndpi->dns_dissect_response = 1).
- In our code, fully parse the DNS response packets using ns_initparse and ns_parserr from libresolv.so.
- Cache those results for some sensible period of time.
- When a flow failed to classify (app_protocol == NDPI_PROTOCOL_UNKNOWN), we check the host_server_name against our DNS cache.  In most cases this results in a match.

I would suggest that if this is to be implemented, it is a feature for ndpiReader and not a feature to be implemented in the nDPI engine.

I can not supply patches because we don't use ndpiReader (we wrote our own front-end).  But if anyone is interested to see how we implemented DNS cahce/hinting, view our [netify-daemon](https://github.com/eglooca/netify-daemon) project.  See the commit log entries related to DNS cache/hinting.

...and again, I can verify that doing this results in significantly higher application detection rates (not just for Netflix) with minimal additional memory overhead.

**Comment by kYroL01** [comment]
@dsokoloski Thanks for the suggestion, but why a DNS feature request could not be added to main engine ?
@khaled-hamwi Can u provide me a pcap to reproduce what are evidenced ? Thanks a lot.

**Comment by dsokoloski** [comment]
@kYroL01 Sorry I wasn't saying it couldn't be done (it should!), just that it will be more complicated to do.

For example, off the top of my head:

- There should only be one global DNS cache that can be accessed and updated by multiple detection threads, otherwise there will be duplicate caches, wasting memory (in our use case, we listen on all LAN and WAN interfaces simultaneously).
- The nDPI engine will have to implement locking to support this (likely via pthread_mutex).
- The nDPI engine will require some mechanism to check for and purge expired address records.  When will that happen; during a call to ndpi_detection_process_packet?

I will clarify again that I think it would be very cool to have this built into the nDPI engine rather than leaving it up to the application, but that it would require more careful work to implement at the API level.  There likely are portability issues to sort out too (libresolv?).

**Comment by kYroL01** [comment]
@dsokoloski Now I understand what u said. Yes, I'm agree with you, but It will be a nice feature to think about for the future. ;)

**Comment by rizwankh** [comment]
@dsokoloski [netify-daemon](https://github.com/eglooca/netify-daemon) is not accessible.

**Comment by dsokoloski** [comment]
@rizwankh My apologies, we have moved to [GitLab](https://gitlab.com/netify.ai/public/netify-agent).

**Comment by IvanNardi** [comment]
This logic has been implemented as FPC
