### ISSUE TITLE
nDPI compilation failure

### ISSUE THREAD

**Issue by marcopp2018** [ntop/nDPI#588]
Hi,
 
  I tried to install nDPI using the following commands:
    cd ~
    cd nDPI
    git clone https://github.com/ntop/nDPI.git
    ./autogen.sh
    make && make install

all commands worked as expected except the make install:

Making install in src/lib
make[1]: Entering directory '/root/nDPI/src/lib'
make[1]: *** No rule to make target 'install'.  Stop.
make[1]: Leaving directory '/root/nDPI/src/lib'
Makefile:468: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

Using 2.2.2 branch works fine

**Comment by genterminl** [comment]
I have the same problem, except I did git clone first, then cd nDPI, ./autogen.sh, make, make install.  
I don't know if it's relevant, but in the main directory, there is a symlink lib pointing to a non-existent src/lib/.libs.  I also note that README.md says to do ./autogen, ./configure, make.  Since autogen already runs configure, isn't that redundant?  Also, there is not any instruction to do "make install" so is it missing, or am I missing something about how this should get installed somewhere where it can be found when compiling ntop.
(I have the same problem with master, 2.2-stable, and 2.2.2-stable.)
Edit: I think the docs need improving.  I finally found in the ntopng/doc/README.compilation a note that implies compiling ntopng will find nDPI, so I suppose it doesn't actually need to be installed.

**Comment by kYroL01** [comment]
@marcopp2018 There's no error on compilation. The compilation works well.
Remember that nDPI is a library, so you cannot "install" it, but you need a program that call nDPI, as [https://github.com/ntop/ntopng](url) .
So as @genterminl said in the Edit, nDPI is found by other programs that use it. Alternatively you can build your own program that call nDPI API.

p.s. @genterminl yes, you're right about ./configure.

**Comment by marcopp2018** [comment]
@kYroL01  
I was trying to use ftflow from the pfring_ft example.

The following commands works without any issue:
    ftflow -i eth0
When using layer 7 commands it fails:

ftflow -i eth0 -7
#########################################################################
 ERROR: You do not seem to have a valid PF_RING FT 7.3.0.180817 license [FF7B9D9E760669E9]
 ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
 We're now working in demo mode with packet capture and
 transmission limited to 5 minutes
#########################################################################
*** ndpi_load_hostname_category not found, please install latest ndpi library ***
*** /usr/local/lib/libndpi.so not found or missing symbols ***
pfring_ft_create_table error


This is the reason I was trying to install the nDPI, in order to create the /usr/local/lib/libndpi.so
How to create the libndpi.so file?

**Comment by dsokoloski** [comment]
@kYroL01 
> Remember that nDPI is a library, so you cannot "install" it, but you need a program that call nDPI, as https://github.com/ntop/ntopng .

I install libraries everyday using `make install` :)  Not sure what you're getting at here...

**Comment by rsolsn** [comment]
i need to install shared library that 2.4 doesn't generate....
