### ISSUE TITLE
Fix problems on the s390x platform

### ISSUE THREAD

**Issue by emanuele-f** [ntop/nDPI#843]
Pull request #840 has introduced the travis build tests on the s390x platform. However, the tests fail as it seems that the nDPI detection logic is affected on that platform. We don't have such a platform so we cannot troubleshoot it. @xnox can you troubleshoot and fix the problems? If we don't have users interested in/supporting the s390x platform we will probably remove it from the travis build.

**Comment by xnox** [comment]
Sure, let me try poking it.

**Comment by xnox** [comment]
Ok, I am observing that on amd64 master on Ubuntu Focal (latest development series) passes correctly and fails spectacularly on s390x.

I'm not quite sure what the testsuite is, so let me state some assumptions for you to check my understanding.

Packet capture was pre-recorded somewhere and stored as test suite input, then it is parsed by the tooling / test case, and compared with known good results. Thus, for example, the expected protocols and directions of upload/download etc should remain the same.

What i'm seeing is as if .pcap captured files have endian ecoding and or not cross-platform. Because for example connections that are expected to happen over `QUIC.Google` get parsed as `QUIC`, those that are supposed to be `QUIC.GMail` end up being `QUIC.Google`, downloads are marked as uploads `<->` expected yet `->` produced, etc.

It feels as if there is like pcap library bug here, or like we need to recreate .pcap files for endianes.

Can you please give me some trivial sample instructions on how to recreate a small .pcap file that is used in a testsuite? Then I'll try to recreate it on s390x and on amd64, and run test against each other, to see if same .pcap files are produced on both arches, and if they are parsed the same way.

Instead of completely disabling s390x build, can we mark it as expected failure (such that it doesn't block any changes) or like for example, not enforce test-suite to pass on big endian? Cause it feels to me that the app seems to sort of work correct on s390x, despite the test. That way at least build is compiled with a big-endian compiler.

**Comment by emanuele-f** [comment]
Hi, the test is composed by a bash script (https://github.com/ntop/nDPI/blob/dev/tests/do.sh) which runs the ndpiReader program over the PCAP files from the https://github.com/ntop/nDPI/tree/dev/tests/pcap directory and checks that the output matches the previosly generated output (https://github.com/ntop/nDPI/tree/dev/tests/result). If the previosly generated output file is missing, a new one is created. You can manually generate the test output with:

`example/ndpiReader -p example/protos.txt -c example/categories.txt -q -i tests/pcap/some_pcap -v2`

**Comment by xnox** [comment]
Ok, but how do I recreate/recapture `tests/pcap/quic.pcap` itself? Or any other test pcap input files?

**Comment by xnox** [comment]
(interested to recreate a failing test case's .pcap file on s390x machine, to see if the test case then matches the amd64 expected output)

**Comment by emanuele-f** [comment]
The pcap file is the test input, you don't need to create it again, you can find it in this repo (e.g. https://github.com/ntop/nDPI/blob/dev/tests/pcap/quic.pcap). pcap files are usually generated with `tcpdump -n -s0 -i wlan0 -w my.pcap`.

In order to perform a test, you can run the ndpiReader command above on any of the example pcap files (or your own pcap file) on both the x64 and the s390x machine and compare the results.

**Comment by lucaderi** [comment]
Won't fix: this is not a platform we currently support
