### ISSUE TITLE
TLS allocated more than 64K for message buffer

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#857]
How large is the memory buffer really needed to determine the parameters of the TLS protocol?
The debugging protocol shows that the size of this buffer can increase to 66399 bytes.
The macro "NDPI_MAX_TLS_REQUEST_SIZE 10000" is not used anywhere.
If only server names need to be determined, is 2048 bytes enough for the buffer?

**Comment by lucaderi** [comment]
This is the max memory used to store in memory a TLS chunk. So this is regardless of what you want to do. I suggest not to change it.

Instead of dissecting only the host names (i.e. the SNI) this is part of the Client Hello, you can just stop yourself as soon as TLS is detected and avoid allocating memory for the certificate.
